version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: pq
      POSTGRES_PASSWORD: pq
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: >
      sh -c "
        until pg_isready -h localhost -p 5432; do
          sleep 1;
        done;
        psql -v ON_ERROR_STOP=1 --username pq --dbname postgres <<-EOSQL
          CREATE DATABASE audit;
          CREATE DATABASE test_audit;
        EOSQL
      "

  audit-system:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=host=db port=5432 user=pq password=pq dbname=audit sslmode=disable
    ports:
      - "8080:8080"

volumes:
  postgres_data:
