// Code generated by ent, DO NOT EDIT.

package ent

import (
	"audit-system/ent/auditlog"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuditLogCreate is the builder for creating a AuditLog entity.
type AuditLogCreate struct {
	config
	mutation *AuditLogMutation
	hooks    []Hook
}

// SetClientID sets the "client_id" field.
func (alc *AuditLogCreate) SetClientID(s string) *AuditLogCreate {
	alc.mutation.SetClientID(s)
	return alc
}

// SetTimestamp sets the "timestamp" field.
func (alc *AuditLogCreate) SetTimestamp(t time.Time) *AuditLogCreate {
	alc.mutation.SetTimestamp(t)
	return alc
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (alc *AuditLogCreate) SetNillableTimestamp(t *time.Time) *AuditLogCreate {
	if t != nil {
		alc.SetTimestamp(*t)
	}
	return alc
}

// SetEntity sets the "entity" field.
func (alc *AuditLogCreate) SetEntity(s string) *AuditLogCreate {
	alc.mutation.SetEntity(s)
	return alc
}

// SetMutation sets the "mutation" field.
func (alc *AuditLogCreate) SetMutation(s string) *AuditLogCreate {
	alc.mutation.SetMutation(s)
	return alc
}

// SetBefore sets the "before" field.
func (alc *AuditLogCreate) SetBefore(m map[string]interface{}) *AuditLogCreate {
	alc.mutation.SetBefore(m)
	return alc
}

// SetAfter sets the "after" field.
func (alc *AuditLogCreate) SetAfter(m map[string]interface{}) *AuditLogCreate {
	alc.mutation.SetAfter(m)
	return alc
}

// Mutation returns the AuditLogMutation object of the builder.
func (alc *AuditLogCreate) Mutation() *AuditLogMutation {
	return alc.mutation
}

// Save creates the AuditLog in the database.
func (alc *AuditLogCreate) Save(ctx context.Context) (*AuditLog, error) {
	alc.defaults()
	return withHooks(ctx, alc.sqlSave, alc.mutation, alc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (alc *AuditLogCreate) SaveX(ctx context.Context) *AuditLog {
	v, err := alc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (alc *AuditLogCreate) Exec(ctx context.Context) error {
	_, err := alc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (alc *AuditLogCreate) ExecX(ctx context.Context) {
	if err := alc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (alc *AuditLogCreate) defaults() {
	if _, ok := alc.mutation.Timestamp(); !ok {
		v := auditlog.DefaultTimestamp()
		alc.mutation.SetTimestamp(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (alc *AuditLogCreate) check() error {
	if _, ok := alc.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "AuditLog.client_id"`)}
	}
	if _, ok := alc.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "AuditLog.timestamp"`)}
	}
	if _, ok := alc.mutation.Entity(); !ok {
		return &ValidationError{Name: "entity", err: errors.New(`ent: missing required field "AuditLog.entity"`)}
	}
	if _, ok := alc.mutation.Mutation(); !ok {
		return &ValidationError{Name: "mutation", err: errors.New(`ent: missing required field "AuditLog.mutation"`)}
	}
	return nil
}

func (alc *AuditLogCreate) sqlSave(ctx context.Context) (*AuditLog, error) {
	if err := alc.check(); err != nil {
		return nil, err
	}
	_node, _spec := alc.createSpec()
	if err := sqlgraph.CreateNode(ctx, alc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	alc.mutation.id = &_node.ID
	alc.mutation.done = true
	return _node, nil
}

func (alc *AuditLogCreate) createSpec() (*AuditLog, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditLog{config: alc.config}
		_spec = sqlgraph.NewCreateSpec(auditlog.Table, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt))
	)
	if value, ok := alc.mutation.ClientID(); ok {
		_spec.SetField(auditlog.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := alc.mutation.Timestamp(); ok {
		_spec.SetField(auditlog.FieldTimestamp, field.TypeTime, value)
		_node.Timestamp = value
	}
	if value, ok := alc.mutation.Entity(); ok {
		_spec.SetField(auditlog.FieldEntity, field.TypeString, value)
		_node.Entity = value
	}
	if value, ok := alc.mutation.Mutation(); ok {
		_spec.SetField(auditlog.FieldMutation, field.TypeString, value)
		_node.Mutation = value
	}
	if value, ok := alc.mutation.Before(); ok {
		_spec.SetField(auditlog.FieldBefore, field.TypeJSON, value)
		_node.Before = value
	}
	if value, ok := alc.mutation.After(); ok {
		_spec.SetField(auditlog.FieldAfter, field.TypeJSON, value)
		_node.After = value
	}
	return _node, _spec
}

// AuditLogCreateBulk is the builder for creating many AuditLog entities in bulk.
type AuditLogCreateBulk struct {
	config
	err      error
	builders []*AuditLogCreate
}

// Save creates the AuditLog entities in the database.
func (alcb *AuditLogCreateBulk) Save(ctx context.Context) ([]*AuditLog, error) {
	if alcb.err != nil {
		return nil, alcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(alcb.builders))
	nodes := make([]*AuditLog, len(alcb.builders))
	mutators := make([]Mutator, len(alcb.builders))
	for i := range alcb.builders {
		func(i int, root context.Context) {
			builder := alcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, alcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, alcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, alcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (alcb *AuditLogCreateBulk) SaveX(ctx context.Context) []*AuditLog {
	v, err := alcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (alcb *AuditLogCreateBulk) Exec(ctx context.Context) error {
	_, err := alcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (alcb *AuditLogCreateBulk) ExecX(ctx context.Context) {
	if err := alcb.Exec(ctx); err != nil {
		panic(err)
	}
}
