// Code generated by ent, DO NOT EDIT.

package ent

import (
	"audit-system/ent/auditlog"
	"audit-system/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuditLogUpdate is the builder for updating AuditLog entities.
type AuditLogUpdate struct {
	config
	hooks    []Hook
	mutation *AuditLogMutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (alu *AuditLogUpdate) Where(ps ...predicate.AuditLog) *AuditLogUpdate {
	alu.mutation.Where(ps...)
	return alu
}

// SetClientID sets the "client_id" field.
func (alu *AuditLogUpdate) SetClientID(s string) *AuditLogUpdate {
	alu.mutation.SetClientID(s)
	return alu
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableClientID(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetClientID(*s)
	}
	return alu
}

// SetTimestamp sets the "timestamp" field.
func (alu *AuditLogUpdate) SetTimestamp(t time.Time) *AuditLogUpdate {
	alu.mutation.SetTimestamp(t)
	return alu
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableTimestamp(t *time.Time) *AuditLogUpdate {
	if t != nil {
		alu.SetTimestamp(*t)
	}
	return alu
}

// SetEntity sets the "entity" field.
func (alu *AuditLogUpdate) SetEntity(s string) *AuditLogUpdate {
	alu.mutation.SetEntity(s)
	return alu
}

// SetNillableEntity sets the "entity" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableEntity(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetEntity(*s)
	}
	return alu
}

// SetMutation sets the "mutation" field.
func (alu *AuditLogUpdate) SetMutation(s string) *AuditLogUpdate {
	alu.mutation.SetMutation(s)
	return alu
}

// SetNillableMutation sets the "mutation" field if the given value is not nil.
func (alu *AuditLogUpdate) SetNillableMutation(s *string) *AuditLogUpdate {
	if s != nil {
		alu.SetMutation(*s)
	}
	return alu
}

// SetBefore sets the "before" field.
func (alu *AuditLogUpdate) SetBefore(m map[string]interface{}) *AuditLogUpdate {
	alu.mutation.SetBefore(m)
	return alu
}

// ClearBefore clears the value of the "before" field.
func (alu *AuditLogUpdate) ClearBefore() *AuditLogUpdate {
	alu.mutation.ClearBefore()
	return alu
}

// SetAfter sets the "after" field.
func (alu *AuditLogUpdate) SetAfter(m map[string]interface{}) *AuditLogUpdate {
	alu.mutation.SetAfter(m)
	return alu
}

// ClearAfter clears the value of the "after" field.
func (alu *AuditLogUpdate) ClearAfter() *AuditLogUpdate {
	alu.mutation.ClearAfter()
	return alu
}

// Mutation returns the AuditLogMutation object of the builder.
func (alu *AuditLogUpdate) Mutation() *AuditLogMutation {
	return alu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (alu *AuditLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, alu.sqlSave, alu.mutation, alu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (alu *AuditLogUpdate) SaveX(ctx context.Context) int {
	affected, err := alu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (alu *AuditLogUpdate) Exec(ctx context.Context) error {
	_, err := alu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (alu *AuditLogUpdate) ExecX(ctx context.Context) {
	if err := alu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (alu *AuditLogUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt))
	if ps := alu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := alu.mutation.ClientID(); ok {
		_spec.SetField(auditlog.FieldClientID, field.TypeString, value)
	}
	if value, ok := alu.mutation.Timestamp(); ok {
		_spec.SetField(auditlog.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := alu.mutation.Entity(); ok {
		_spec.SetField(auditlog.FieldEntity, field.TypeString, value)
	}
	if value, ok := alu.mutation.Mutation(); ok {
		_spec.SetField(auditlog.FieldMutation, field.TypeString, value)
	}
	if value, ok := alu.mutation.Before(); ok {
		_spec.SetField(auditlog.FieldBefore, field.TypeJSON, value)
	}
	if alu.mutation.BeforeCleared() {
		_spec.ClearField(auditlog.FieldBefore, field.TypeJSON)
	}
	if value, ok := alu.mutation.After(); ok {
		_spec.SetField(auditlog.FieldAfter, field.TypeJSON, value)
	}
	if alu.mutation.AfterCleared() {
		_spec.ClearField(auditlog.FieldAfter, field.TypeJSON)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, alu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	alu.mutation.done = true
	return n, nil
}

// AuditLogUpdateOne is the builder for updating a single AuditLog entity.
type AuditLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditLogMutation
}

// SetClientID sets the "client_id" field.
func (aluo *AuditLogUpdateOne) SetClientID(s string) *AuditLogUpdateOne {
	aluo.mutation.SetClientID(s)
	return aluo
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableClientID(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetClientID(*s)
	}
	return aluo
}

// SetTimestamp sets the "timestamp" field.
func (aluo *AuditLogUpdateOne) SetTimestamp(t time.Time) *AuditLogUpdateOne {
	aluo.mutation.SetTimestamp(t)
	return aluo
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableTimestamp(t *time.Time) *AuditLogUpdateOne {
	if t != nil {
		aluo.SetTimestamp(*t)
	}
	return aluo
}

// SetEntity sets the "entity" field.
func (aluo *AuditLogUpdateOne) SetEntity(s string) *AuditLogUpdateOne {
	aluo.mutation.SetEntity(s)
	return aluo
}

// SetNillableEntity sets the "entity" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableEntity(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetEntity(*s)
	}
	return aluo
}

// SetMutation sets the "mutation" field.
func (aluo *AuditLogUpdateOne) SetMutation(s string) *AuditLogUpdateOne {
	aluo.mutation.SetMutation(s)
	return aluo
}

// SetNillableMutation sets the "mutation" field if the given value is not nil.
func (aluo *AuditLogUpdateOne) SetNillableMutation(s *string) *AuditLogUpdateOne {
	if s != nil {
		aluo.SetMutation(*s)
	}
	return aluo
}

// SetBefore sets the "before" field.
func (aluo *AuditLogUpdateOne) SetBefore(m map[string]interface{}) *AuditLogUpdateOne {
	aluo.mutation.SetBefore(m)
	return aluo
}

// ClearBefore clears the value of the "before" field.
func (aluo *AuditLogUpdateOne) ClearBefore() *AuditLogUpdateOne {
	aluo.mutation.ClearBefore()
	return aluo
}

// SetAfter sets the "after" field.
func (aluo *AuditLogUpdateOne) SetAfter(m map[string]interface{}) *AuditLogUpdateOne {
	aluo.mutation.SetAfter(m)
	return aluo
}

// ClearAfter clears the value of the "after" field.
func (aluo *AuditLogUpdateOne) ClearAfter() *AuditLogUpdateOne {
	aluo.mutation.ClearAfter()
	return aluo
}

// Mutation returns the AuditLogMutation object of the builder.
func (aluo *AuditLogUpdateOne) Mutation() *AuditLogMutation {
	return aluo.mutation
}

// Where appends a list predicates to the AuditLogUpdate builder.
func (aluo *AuditLogUpdateOne) Where(ps ...predicate.AuditLog) *AuditLogUpdateOne {
	aluo.mutation.Where(ps...)
	return aluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aluo *AuditLogUpdateOne) Select(field string, fields ...string) *AuditLogUpdateOne {
	aluo.fields = append([]string{field}, fields...)
	return aluo
}

// Save executes the query and returns the updated AuditLog entity.
func (aluo *AuditLogUpdateOne) Save(ctx context.Context) (*AuditLog, error) {
	return withHooks(ctx, aluo.sqlSave, aluo.mutation, aluo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aluo *AuditLogUpdateOne) SaveX(ctx context.Context) *AuditLog {
	node, err := aluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aluo *AuditLogUpdateOne) Exec(ctx context.Context) error {
	_, err := aluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aluo *AuditLogUpdateOne) ExecX(ctx context.Context) {
	if err := aluo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (aluo *AuditLogUpdateOne) sqlSave(ctx context.Context) (_node *AuditLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(auditlog.Table, auditlog.Columns, sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeInt))
	id, ok := aluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditlog.FieldID)
		for _, f := range fields {
			if !auditlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aluo.mutation.ClientID(); ok {
		_spec.SetField(auditlog.FieldClientID, field.TypeString, value)
	}
	if value, ok := aluo.mutation.Timestamp(); ok {
		_spec.SetField(auditlog.FieldTimestamp, field.TypeTime, value)
	}
	if value, ok := aluo.mutation.Entity(); ok {
		_spec.SetField(auditlog.FieldEntity, field.TypeString, value)
	}
	if value, ok := aluo.mutation.Mutation(); ok {
		_spec.SetField(auditlog.FieldMutation, field.TypeString, value)
	}
	if value, ok := aluo.mutation.Before(); ok {
		_spec.SetField(auditlog.FieldBefore, field.TypeJSON, value)
	}
	if aluo.mutation.BeforeCleared() {
		_spec.ClearField(auditlog.FieldBefore, field.TypeJSON)
	}
	if value, ok := aluo.mutation.After(); ok {
		_spec.SetField(auditlog.FieldAfter, field.TypeJSON, value)
	}
	if aluo.mutation.AfterCleared() {
		_spec.ClearField(auditlog.FieldAfter, field.TypeJSON)
	}
	_node = &AuditLog{config: aluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	aluo.mutation.done = true
	return _node, nil
}
