// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// AuditLog is the predicate function for auditlog builders.
type AuditLog func(*sql.Selector)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
